FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    git \
    && apt-get clean \
    && rm -rf var\lib\apt\lists\*

WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
COPY media/ /app/media/

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

CMD ["python", "main.py"]